// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/contactForm.ts";
import * as $$$$$$$$$1 from "./actions/contactFormConvex.ts";
import * as $$$$$$$$$2 from "./actions/contactFormConvexFixed.ts";
import * as $$$$$$$$$3 from "./actions/contactFormSimple.ts";
import * as $$$$$$$$$4 from "./actions/submitContact.ts";
import * as $$$$$$$$$5 from "./actions/submitToConvex.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Benefits.tsx";
import * as $$$$$$1 from "./sections/BlogPost.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/ContactForm.tsx";
import * as $$$$$$4 from "./sections/ContactFormBypass.tsx";
import * as $$$$$$5 from "./sections/ContactFormConvex.tsx";
import * as $$$$$$6 from "./sections/ContactFormDebug.tsx";
import * as $$$$$$7 from "./sections/ContactFormDirect.tsx";
import * as $$$$$$8 from "./sections/ContactFormFinal.tsx";
import * as $$$$$$9 from "./sections/ContactFormHybrid.tsx";
import * as $$$$$$10 from "./sections/ContactFormSimple.tsx";
import * as $$$$$$11 from "./sections/ContactFormStyled.tsx";
import * as $$$$$$12 from "./sections/ContactFormTest.tsx";
import * as $$$$$$13 from "./sections/ContactFormVanilla.tsx";
import * as $$$$$$14 from "./sections/ContactFormWorking.tsx";
import * as $$$$$$15 from "./sections/Derivative.tsx";
import * as $$$$$$16 from "./sections/Faq.tsx";
import * as $$$$$$17 from "./sections/Footer.tsx";
import * as $$$$$$18 from "./sections/FormsFooter.tsx";
import * as $$$$$$19 from "./sections/Header.tsx";
import * as $$$$$$20 from "./sections/Hero.tsx";
import * as $$$$$$21 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$22 from "./sections/Logos.tsx";
import * as $$$$$$23 from "./sections/MainPost.tsx";
import * as $$$$$$24 from "./sections/Mission.tsx";
import * as $$$$$$25 from "./sections/NetworkRecoverySteps.tsx";
import * as $$$$$$26 from "./sections/ScrollBlurAlwaysOn.tsx";
import * as $$$$$$27 from "./sections/ScrollBlurCSS.tsx";
import * as $$$$$$28 from "./sections/ScrollBlurDynamic.tsx";
import * as $$$$$$29 from "./sections/ScrollBlurEffect.tsx";
import * as $$$$$$30 from "./sections/ScrollBlurGradient.tsx";
import * as $$$$$$31 from "./sections/ScrollBlurGradient2.tsx";
import * as $$$$$$32 from "./sections/ScrollBlurHybrid.tsx";
import * as $$$$$$33 from "./sections/ScrollBlurLayered.tsx";
import * as $$$$$$34 from "./sections/ScrollBlurPure.tsx";
import * as $$$$$$35 from "./sections/ScrollBlurSimple.tsx";
import * as $$$$$$36 from "./sections/ScrollBlurTest.tsx";
import * as $$$$$$37 from "./sections/Services.tsx";
import * as $$$$$$38 from "./sections/Supporters.tsx";
import * as $$$$$$39 from "./sections/Testimonials.tsx";
import * as $$$$$$40 from "./sections/Theme/Theme.tsx";
import * as $$$$$$41 from "./sections/UnicornStudioEffect.tsx";

const manifest = {
  "sections": {
    "site/sections/Benefits.tsx": $$$$$$0,
    "site/sections/BlogPost.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/ContactForm.tsx": $$$$$$3,
    "site/sections/ContactFormBypass.tsx": $$$$$$4,
    "site/sections/ContactFormConvex.tsx": $$$$$$5,
    "site/sections/ContactFormDebug.tsx": $$$$$$6,
    "site/sections/ContactFormDirect.tsx": $$$$$$7,
    "site/sections/ContactFormFinal.tsx": $$$$$$8,
    "site/sections/ContactFormHybrid.tsx": $$$$$$9,
    "site/sections/ContactFormSimple.tsx": $$$$$$10,
    "site/sections/ContactFormStyled.tsx": $$$$$$11,
    "site/sections/ContactFormTest.tsx": $$$$$$12,
    "site/sections/ContactFormVanilla.tsx": $$$$$$13,
    "site/sections/ContactFormWorking.tsx": $$$$$$14,
    "site/sections/Derivative.tsx": $$$$$$15,
    "site/sections/Faq.tsx": $$$$$$16,
    "site/sections/Footer.tsx": $$$$$$17,
    "site/sections/FormsFooter.tsx": $$$$$$18,
    "site/sections/Header.tsx": $$$$$$19,
    "site/sections/Hero.tsx": $$$$$$20,
    "site/sections/ImageWithParagraph.tsx": $$$$$$21,
    "site/sections/Logos.tsx": $$$$$$22,
    "site/sections/MainPost.tsx": $$$$$$23,
    "site/sections/Mission.tsx": $$$$$$24,
    "site/sections/NetworkRecoverySteps.tsx": $$$$$$25,
    "site/sections/ScrollBlurAlwaysOn.tsx": $$$$$$26,
    "site/sections/ScrollBlurCSS.tsx": $$$$$$27,
    "site/sections/ScrollBlurDynamic.tsx": $$$$$$28,
    "site/sections/ScrollBlurEffect.tsx": $$$$$$29,
    "site/sections/ScrollBlurGradient.tsx": $$$$$$30,
    "site/sections/ScrollBlurGradient2.tsx": $$$$$$31,
    "site/sections/ScrollBlurHybrid.tsx": $$$$$$32,
    "site/sections/ScrollBlurLayered.tsx": $$$$$$33,
    "site/sections/ScrollBlurPure.tsx": $$$$$$34,
    "site/sections/ScrollBlurSimple.tsx": $$$$$$35,
    "site/sections/ScrollBlurTest.tsx": $$$$$$36,
    "site/sections/Services.tsx": $$$$$$37,
    "site/sections/Supporters.tsx": $$$$$$38,
    "site/sections/Testimonials.tsx": $$$$$$39,
    "site/sections/Theme/Theme.tsx": $$$$$$40,
    "site/sections/UnicornStudioEffect.tsx": $$$$$$41,
  },
  "actions": {
    "site/actions/contactForm.ts": $$$$$$$$$0,
    "site/actions/contactFormConvex.ts": $$$$$$$$$1,
    "site/actions/contactFormConvexFixed.ts": $$$$$$$$$2,
    "site/actions/contactFormSimple.ts": $$$$$$$$$3,
    "site/actions/submitContact.ts": $$$$$$$$$4,
    "site/actions/submitToConvex.ts": $$$$$$$$$5,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/records.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
